from .general_agent.subagent import call_general_agent
from .sample_agent.subagent import call_sample_agent
from .cie_to_color_agent.subagent import call_cie_to_color_agent
from .phosphor_lookup_agent.subagent import call_phosphor_lookup_agent