from .general_agent.subagent import call_general_agent
from .sample_agent.subagent import call_sample_agent
from .phosphor_lookup_agent.subagent import call_phosphor_lookup_agent
from .recommend_agent.subagent import call_recommend_agent
from .mp_POSCAR_maker_agent.subagent import call_mp_poscar_maker_agent
from .color_trend_agent.subagent import call_color_trend_agent
