from .phosphor_lookup_agent.subagent import call_phosphor_lookup_agent
from .recommend_agent.subagent import call_recommend_agent
from .color_trend_agent.subagent import call_color_trend_agent
from .MatDX_trend_agent.subagent import call_matdx_trend_agent
from .Phosphor_trend_agent.subagent import call_phosphor_trend_agent
from .estm_trend_agent.subagent import call_estm_trend_agent
from .Phosphor_data_research_agent.subagent import call_phosphor_data_research_agent
from .trend_agent.subagent import call_trend_agent
